### ISSUE TITLE
Support for Isaac gym

### ISSUE THREAD

**Issue by linchangyi1** [osheraz/allsight_sim#2]
Hi @osheraz,

Great implementation. It's exciting to see a demo showing the dexterous hand with tactile sensing in Isaac Gym. I would like to ask whether you have released the code of that part?

Thanks a lot for your reply~

**Comment by osheraz** [comment]
Hi @linchangyi1 ,

Thanks! Actually, I haven't officially released it yet due to other priorities. You can take a look here, but it's still a bit messy:
https://github.com/osheraz/IsaacGymInsertion
The most up-to-date branches are `dev-kinova\align\2finger`

Anyway, my implementation still needs improvement for parallel computing. I highly recommend taking a look at a newer implementation I came across, which looks great:
https://iakinola23.github.io/tacsl/

Good luck!

**Comment by linchangyi1** [comment]
Thank you very much. That helps a lot~
